### PR TITLE
DWAVE Sampler Integration in CaloQVAE framework

### PR DESCRIPTION
**Pull request by Sehmimul**
In this PR the **main changes** are: 

1.  The DWAVE QPU sampler (with the full effective temperature estimation procedure) has been fully integrated in the gumboltCaloCRBM model. 
2.  New version of engine (`EngineCaloQV1`) has been added and it contains training, testing and validation utilities for sampling from the QPU. 
3.   The QPU can now be called at epochs specified in the `d_wave_config.yaml` file. Images can also be generated at specific epochs which need to be specified in the `config.yaml` file. 
4.  Option added to constrain local field and couplings of qubits in DWAVE. Currently no constraining is done. 
5.  DWAVE sample energy and Auxiliary RBM sample energy histograms and corresponding energy data are saved in the output directory and can be retrieved using the `recover_saved_parameters` method of `nbutils`. 

The **minor changes** are:

- https://github.com/QaloSim/CaloQVAE/issues/3#issue-1446565205 has been resolved
- Custom Block Gibbs Sampling steps can now be used. If no custom BGS steps are provided, the default `n_gibbs_sampling_steps` of `dvaecalo_training.yaml` will be used.

### CODE REVIEW

**Comment by BlazerJia1995** [comment]
I tested the constrained-d-wave-sampling branch and  it works. Cheers!

**Comment by Sehmimul** [comment]
> I tested the constrained-d-wave-sampling branch and it works. Cheers!

Thanks!

**Comment by BlazerJia1995** [comment]
@abhishekabhishek Wait a second, I have a question and please hold this request before the group meeting.

**Comment by Sehmimul** [comment]
Major updates since initial comment:
1. https://github.com/QaloSim/CaloQVAE/issues/3 and https://github.com/QaloSim/CaloQVAE/issues/6 fixed.
2. Energy slicing and plotting code added by @BlazerJia1995 
3. Binary Classification files and energy histogram plotting functions added
4. Saved models, synthetic images and beta estimation parameters can be loaded from `fast_scratch_1/CaloData`
5. Feature added in `gumboltCaloCRBM` model to optionally generate all samples from the QPU during validaton.

**Pull request closed without merging**
